# Generated by Django 5.1.1 on 2024-09-15 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libary', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Type',
            new_name='Book_type',
        ),
    ]
