# Generated by Django 5.1.1 on 2024-09-15 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libary', '0002_rename_type_book_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='picture',
            field=models.ImageField(blank=True, upload_to='book_pictures/%Y/%m'),
        ),
    ]
