# Generated by Django 5.1.1 on 2024-09-15 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libary', '0004_genre_alter_collection_year_collection_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='picture',
            field=models.ImageField(upload_to='book_pictures/%Y/%m'),
        ),
    ]
